FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY target/EmployeeCrudCucumberTesting-0.0.1-SNAPSHOT.jar EmployeeCrudCucumberTesting-0.0.1-SNAPSHOT.jar
EXPOSE 8084
CMD ["java","-jar","EmployeeCrudCucumberTesting-0.0.1-SNAPSHOT.jar"]